// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eMeetup.Modules.Events.Infrastructure.Database;

#nullable disable

namespace eMeetup.Modules.Events.Infrastructure.Database.Migrations
{
    [DbContext(typeof(EventsDbContext))]
    [Migration("20260410125123_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("events")
                .HasAnnotation("ProductVersion", "10.0.0-rc.1.25451.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eMeetup.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "events");
                });

            modelBuilder.Entity("eMeetup.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "events");
                });

            modelBuilder.Entity("eMeetup.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "events");
                });

            modelBuilder.Entity("eMeetup.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "events");
                });

            modelBuilder.Entity("eMeetup.Modules.Events.Domain.EventSessions.EventSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("canceled_at");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<double?>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locality");

                    b.Property<double?>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_event_sessions");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_event_sessions_event_id");

                    b.HasIndex("StartsAtUtc")
                        .HasDatabaseName("ix_event_sessions_starts_at_utc");

                    b.HasIndex("EventId", "Status")
                        .HasDatabaseName("ix_event_sessions_event_status");

                    b.HasIndex("Status", "StartsAtUtc")
                        .HasDatabaseName("ix_event_sessions_status_start_date");

                    b.ToTable("event_sessions", "events");
                });

            modelBuilder.Entity("eMeetup.Modules.Events.Domain.EventTags.EventTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("Id")
                        .HasName("pk_event_tags");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_event_tags_event_id");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_event_tags_tag_id");

                    b.ToTable("event_tags", "events");
                });

            modelBuilder.Entity("eMeetup.Modules.Events.Domain.Events.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizer_id");

                    b.Property<string>("OrganizerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organizer_name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.ToTable("events", "events");
                });

            modelBuilder.Entity("eMeetup.Modules.Events.Domain.MateTypes.MateType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AllocatedSlots")
                        .HasColumnType("integer")
                        .HasColumnName("allocated_slots");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("EventSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_session_id");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("integer")
                        .HasColumnName("max_age");

                    b.Property<int?>("MinAge")
                        .HasColumnType("integer")
                        .HasColumnName("min_age");

                    b.Property<string>("PreferredAgeRange")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("preferred_age_range");

                    b.Property<int?>("PreferredGender")
                        .HasColumnType("integer")
                        .HasColumnName("preferred_gender");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_mate_types");

                    b.HasIndex("EventSessionId")
                        .HasDatabaseName("ix_mate_types_event_session_id");

                    b.HasIndex("Gender")
                        .HasDatabaseName("ix_mate_types_gender");

                    b.HasIndex("EventSessionId", "Priority")
                        .HasDatabaseName("ix_mate_types_session_priority");

                    b.ToTable("mate_types", "events");
                });

            modelBuilder.Entity("eMeetup.Modules.Events.Domain.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("slug");

                    b.Property<Guid?>("TagGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_group_id");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("usage_count");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_tags_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_slug");

                    b.HasIndex("TagGroupId")
                        .HasDatabaseName("ix_tags_tag_group_id");

                    b.HasIndex("UsageCount")
                        .HasDatabaseName("ix_tags_usage_count");

                    b.ToTable("tags", "events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-aaaaaaaaaaaa"),
                            Description = "Занятия бегом и пробежки",
                            IsActive = true,
                            Name = "Бег",
                            Slug = "бег",
                            TagGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-bbbbbbbbbbbb"),
                            Description = "Тренировки в бассейне",
                            IsActive = true,
                            Name = "Плавание",
                            Slug = "плавание",
                            TagGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-cccccccccccc"),
                            Description = "Поездки по городу и шоссе",
                            IsActive = true,
                            Name = "Велоспорт",
                            Slug = "велоспорт",
                            TagGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-dddddddddddd"),
                            Description = "Фитнес и силовые тренировки",
                            IsActive = true,
                            Name = "Тренажерный зал",
                            Slug = "тренажерный-зал",
                            TagGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-eeeeeeeeeeee"),
                            Description = "Занятия йогой и растяжка",
                            IsActive = true,
                            Name = "Йога",
                            Slug = "йога",
                            TagGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-aaaaaaaaaaaa"),
                            Description = "Катание на склонах",
                            IsActive = true,
                            Name = "Горные лыжи",
                            Slug = "горные-лыжи",
                            TagGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-bbbbbbbbbbbb"),
                            Description = "Скандинавская ходьба на лыжах по трассам",
                            IsActive = true,
                            Name = "Беговые лыжи",
                            Slug = "беговые-лыжи",
                            TagGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-cccccccccccc"),
                            Description = "Катание на склонах и в парках",
                            IsActive = true,
                            Name = "Сноуборд",
                            Slug = "сноуборд",
                            TagGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-dddddddddddd"),
                            Description = "Катание на ледовых катках",
                            IsActive = true,
                            Name = "Катание на коньках",
                            Slug = "катание-на-коньках",
                            TagGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-eeeeeeeeeeee"),
                            Description = "Катание на ватрушках с горок",
                            IsActive = true,
                            Name = "Тюбинг",
                            Slug = "тюбинг",
                            TagGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-ffffffffffff"),
                            Description = "Походы на снегоступах",
                            IsActive = true,
                            Name = "Зимний поход",
                            Slug = "зимний-поход",
                            TagGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-aaaaaaaaaaaa"),
                            Description = "Дневные походы по тропам",
                            IsActive = true,
                            Name = "Поход",
                            Slug = "поход",
                            TagGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-bbbbbbbbbbbb"),
                            Description = "Многодневные велосипедные путешествия",
                            IsActive = true,
                            Name = "Велотур",
                            Slug = "велотур",
                            TagGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-cccccccccccc"),
                            Description = "Трапезы на природе",
                            IsActive = true,
                            Name = "Пикник",
                            Slug = "пикник",
                            TagGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-dddddddddddd"),
                            Description = "Ночёвки на природе",
                            IsActive = true,
                            Name = "Кемпинг",
                            Slug = "кемпинг",
                            TagGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-eeeeeeeeeeee"),
                            Description = "Бег по природным тропам",
                            IsActive = true,
                            Name = "Трейлраннинг",
                            Slug = "трейлраннинг",
                            TagGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-aaaaaaaaaaaa"),
                            Description = "Сплав на лёгких надувных лодках",
                            IsActive = true,
                            Name = "Пакрафтинг",
                            Slug = "пакрафтинг",
                            TagGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-bbbbbbbbbbbb"),
                            Description = "Катание на доске с веслом стоя",
                            IsActive = true,
                            Name = "САП-сёрфинг",
                            Slug = "сап-сёрфинг",
                            TagGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-cccccccccccc"),
                            Description = "Сплав на каяках по рекам и озёрам",
                            IsActive = true,
                            Name = "Каякинг",
                            Slug = "каякинг",
                            TagGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-dddddddddddd"),
                            Description = "Путешествия на каноэ по спокойной воде",
                            IsActive = true,
                            Name = "Каноэ",
                            Slug = "каноэ",
                            TagGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-eeeeeeeeeeee"),
                            Description = "Сплав по бурной воде",
                            IsActive = true,
                            Name = "Рафтинг",
                            Slug = "рафтинг",
                            TagGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-ffffffffffff"),
                            Description = "Плавание в озёрах и морях",
                            IsActive = true,
                            Name = "Плавание на открытой воде",
                            Slug = "плавание-на-открытой-воде",
                            TagGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-aaaaaaaaaaaa"),
                            Description = "Фестивали живой музыки и концертов",
                            IsActive = true,
                            Name = "Музыкальный фестиваль",
                            Slug = "музыкальный-фестиваль",
                            TagGroupId = new Guid("55555555-5555-5555-5555-555555555555"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-bbbbbbbbbbbb"),
                            Description = "Кулинарные мероприятия",
                            IsActive = true,
                            Name = "Гастрофестиваль",
                            Slug = "гастрофестиваль",
                            TagGroupId = new Guid("55555555-5555-5555-5555-555555555555"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-cccccccccccc"),
                            Description = "Традиционные праздники",
                            IsActive = true,
                            Name = "Культурный фестиваль",
                            Slug = "культурный-фестиваль",
                            TagGroupId = new Guid("55555555-5555-5555-5555-555555555555"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-dddddddddddd"),
                            Description = "Местные ярмарки и гуляния",
                            IsActive = true,
                            Name = "Городской праздник",
                            Slug = "городской-праздник",
                            TagGroupId = new Guid("55555555-5555-5555-5555-555555555555"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-eeeeeeeeeeee"),
                            Description = "Дегустации крафтового пива",
                            IsActive = true,
                            Name = "Пивной фестиваль",
                            Slug = "пивной-фестиваль",
                            TagGroupId = new Guid("55555555-5555-5555-5555-555555555555"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-aaaaaaaaaaaa"),
                            Description = "Осмотр достопримечательностей",
                            IsActive = true,
                            Name = "Городская поездка",
                            Slug = "городская-поездка",
                            TagGroupId = new Guid("66666666-6666-6666-6666-666666666666"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-bbbbbbbbbbbb"),
                            Description = "Кулинарные и винные туры",
                            IsActive = true,
                            Name = "Гастротур",
                            Slug = "гастротур",
                            TagGroupId = new Guid("66666666-6666-6666-6666-666666666666"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-cccccccccccc"),
                            Description = "Путешествия на машине",
                            IsActive = true,
                            Name = "Автопутешествие",
                            Slug = "автопутешествие",
                            TagGroupId = new Guid("66666666-6666-6666-6666-666666666666"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-dddddddddddd"),
                            Description = "Экскурсии по музеям и архитектуре",
                            IsActive = true,
                            Name = "Культурный тур",
                            Slug = "культурный-тур",
                            TagGroupId = new Guid("66666666-6666-6666-6666-666666666666"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-eeeeeeeeeeee"),
                            Description = "Короткие поездки за город",
                            IsActive = true,
                            Name = "Уикенд за городом",
                            Slug = "уикенд-за-городом",
                            TagGroupId = new Guid("66666666-6666-6666-6666-666666666666"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-aaaaaaaaaaaa"),
                            Description = "Фильмы и кинопоказы",
                            IsActive = true,
                            Name = "Кино",
                            Slug = "кино",
                            TagGroupId = new Guid("77777777-7777-7777-7777-777777777777"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-bbbbbbbbbbbb"),
                            Description = "Спектакли и театральные постановки",
                            IsActive = true,
                            Name = "Театр",
                            Slug = "театр",
                            TagGroupId = new Guid("77777777-7777-7777-7777-777777777777"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-cccccccccccc"),
                            Description = "Концерты живой музыки",
                            IsActive = true,
                            Name = "Концерт",
                            Slug = "концерт",
                            TagGroupId = new Guid("77777777-7777-7777-7777-777777777777"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-dddddddddddd"),
                            Description = "Рок и метал концерты",
                            IsActive = true,
                            Name = "Рок-концерт",
                            Slug = "рок-концерт",
                            TagGroupId = new Guid("77777777-7777-7777-7777-777777777777"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-eeeeeeeeeeee"),
                            Description = "Художественные галереи и выставки",
                            IsActive = true,
                            Name = "Выставка искусств",
                            Slug = "выставка-искусств",
                            TagGroupId = new Guid("77777777-7777-7777-7777-777777777777"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-ffffffffffff"),
                            Description = "Юмористические выступления",
                            IsActive = true,
                            Name = "Стендап",
                            Slug = "стендап",
                            TagGroupId = new Guid("77777777-7777-7777-7777-777777777777"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-aaaaaaaaaaaa"),
                            Description = "Встречи в барах и пабах",
                            IsActive = true,
                            Name = "Паб",
                            Slug = "паб",
                            TagGroupId = new Guid("88888888-8888-8888-8888-888888888888"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-bbbbbbbbbbbb"),
                            Description = "Летние кафе и террасы",
                            IsActive = true,
                            Name = "Веранда",
                            Slug = "веранда",
                            TagGroupId = new Guid("88888888-8888-8888-8888-888888888888"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-cccccccccccc"),
                            Description = "Неформальные встречи за кофе",
                            IsActive = true,
                            Name = "Кофе-дейт",
                            Slug = "кофе-дейт",
                            TagGroupId = new Guid("88888888-8888-8888-8888-888888888888"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-dddddddddddd"),
                            Description = "Вечера настольных игр",
                            IsActive = true,
                            Name = "Настольные игры",
                            Slug = "настольные-игры",
                            TagGroupId = new Guid("88888888-8888-8888-8888-888888888888"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-eeeeeeeeeeee"),
                            Description = "Неспешные встречи в парке",
                            IsActive = true,
                            Name = "Пикник в парке",
                            Slug = "пикник-в-парке",
                            TagGroupId = new Guid("88888888-8888-8888-8888-888888888888"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-ffffffffffff"),
                            Description = "Расслабленный летний отдых в гамаке на природе",
                            IsActive = true,
                            Name = "Отдых в гамаке",
                            Slug = "отдых-в-гамаке",
                            TagGroupId = new Guid("88888888-8888-8888-8888-888888888888"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-aaaaaaaaaaaa"),
                            Description = "Соревнования по плаванию, велоспорту и бегу",
                            IsActive = true,
                            Name = "Триатлон",
                            Slug = "триатлон",
                            TagGroupId = new Guid("99999999-9999-9999-9999-999999999999"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-bbbbbbbbbbbb"),
                            Description = "Участие в марафонах в других городах",
                            IsActive = true,
                            Name = "Марафон",
                            Slug = "марафон",
                            TagGroupId = new Guid("99999999-9999-9999-9999-999999999999"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-cccccccccccc"),
                            Description = "Забеги с препятствиями",
                            IsActive = true,
                            Name = "Гонка с препятствиями",
                            Slug = "гонка-с-препятствиями",
                            TagGroupId = new Guid("99999999-9999-9999-9999-999999999999"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-dddddddddddd"),
                            Description = "Соревновательные велозаезды",
                            IsActive = true,
                            Name = "Велосипедная гонка",
                            Slug = "велосипедная-гонка",
                            TagGroupId = new Guid("99999999-9999-9999-9999-999999999999"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-eeeeeeeeeeee"),
                            Description = "Заплывы на открытой воде или в бассейне",
                            IsActive = true,
                            Name = "Соревнования по плаванию",
                            Slug = "соревнования-по-плаванию",
                            TagGroupId = new Guid("99999999-9999-9999-9999-999999999999"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-ffffffffffff"),
                            Description = "Соревнования по бегу по бездорожью",
                            IsActive = true,
                            Name = "Трейловый забег",
                            Slug = "трейловый-забег",
                            TagGroupId = new Guid("99999999-9999-9999-9999-999999999999"),
                            UsageCount = 0
                        });
                });

            modelBuilder.Entity("eMeetup.Modules.Events.Domain.Tags.TagGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tag_groups");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_tag_groups_display_order");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_tag_groups_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tag_groups_name");

                    b.ToTable("tag_groups", "events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Бег, плавание, велоспорт и другие спортивные активности",
                            DisplayOrder = 1,
                            Icon = "🏃",
                            IsActive = true,
                            Name = "Активный образ жизни"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Лыжи, сноуборд, коньки и тюбинг",
                            DisplayOrder = 2,
                            Icon = "❄️",
                            IsActive = true,
                            Name = "Зимние активности"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Походы, велотуры и пикники на природе",
                            DisplayOrder = 3,
                            Icon = "⛰️",
                            IsActive = true,
                            Name = "Приключения и активный отдых"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Пакрафтинг, САП, каякинг и другие водные походы",
                            DisplayOrder = 4,
                            Icon = "🚣",
                            IsActive = true,
                            Name = "Водные приключения"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Музыкальные, гастрономические и культурные фестивали",
                            DisplayOrder = 5,
                            Icon = "🎪",
                            IsActive = true,
                            Name = "Фестивали и мероприятия"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Городские поездки, экскурсии, гастротуры и автопутешествия",
                            DisplayOrder = 6,
                            Icon = "✈️",
                            IsActive = true,
                            Name = "Путешествия"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Description = "Кино, театр, концерты и рок-шоу",
                            DisplayOrder = 7,
                            Icon = "🎭",
                            IsActive = true,
                            Name = "Культура и развлечения"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Description = "Встречи в пабах, летние веранды и приятное времяпрепровождение",
                            DisplayOrder = 8,
                            Icon = "😎",
                            IsActive = true,
                            Name = "Отдых и тусовки"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Description = "Марафоны, триатлоны, соревнования и забеги в других городах",
                            DisplayOrder = 9,
                            Icon = "🏆",
                            IsActive = true,
                            Name = "Спортивные события"
                        });
                });

            modelBuilder.Entity("eMeetup.Modules.Events.Domain.EventSessions.EventSession", b =>
                {
                    b.HasOne("eMeetup.Modules.Events.Domain.Events.Event", "Event")
                        .WithMany("Sessions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_session_event");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("eMeetup.Modules.Events.Domain.EventTags.EventTag", b =>
                {
                    b.HasOne("eMeetup.Modules.Events.Domain.Events.Event", "Event")
                        .WithMany("Tags")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_tags_events_event_id");

                    b.HasOne("eMeetup.Modules.Events.Domain.Tags.Tag", "Tag")
                        .WithMany("EventTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_tags_tags_tag_id");

                    b.Navigation("Event");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("eMeetup.Modules.Events.Domain.MateTypes.MateType", b =>
                {
                    b.HasOne("eMeetup.Modules.Events.Domain.EventSessions.EventSession", null)
                        .WithMany()
                        .HasForeignKey("EventSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mate_type_event_session");
                });

            modelBuilder.Entity("eMeetup.Modules.Events.Domain.Tags.Tag", b =>
                {
                    b.HasOne("eMeetup.Modules.Events.Domain.Tags.TagGroup", "TagGroup")
                        .WithMany("Tags")
                        .HasForeignKey("TagGroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tags_tag_group_tag_group_id");

                    b.Navigation("TagGroup");
                });

            modelBuilder.Entity("eMeetup.Modules.Events.Domain.Events.Event", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("eMeetup.Modules.Events.Domain.Tags.Tag", b =>
                {
                    b.Navigation("EventTags");
                });

            modelBuilder.Entity("eMeetup.Modules.Events.Domain.Tags.TagGroup", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
