<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Authorization\PermissionService.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\eMeetup.Common.Infrastructure\eMeetup.Common.Infrastructure.csproj" />
    <ProjectReference Include="..\eMeetup.Modules.Enrolls.Application\eMeetup.Modules.Enrolls.Application.csproj" />
    <ProjectReference Include="..\eMeetup.Modules.Enrolls.Presentation\eMeetup.Modules.Enrolls.Presentation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Authorization\" />
  </ItemGroup>

</Project>
