// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eMeetup.Modules.Users.Infrastructure.Database;

#nullable disable

namespace eMeetup.Modules.Users.Infrastructure.Database.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20260301165619_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("users")
                .HasAnnotation("ProductVersion", "10.0.0-rc.1.25451.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<string>("PermissionCode")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission_code");

                    b.Property<string>("RoleName")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("PermissionCode", "RoleName")
                        .HasName("pk_role_permissions");

                    b.HasIndex("RoleName")
                        .HasDatabaseName("ix_role_permissions_role_name");

                    b.ToTable("role_permissions", "users");

                    b.HasData(
                        new
                        {
                            PermissionCode = "users:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "users:update",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "tags:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "users:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "users:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "tags:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "event-statistics:read",
                            RoleName = "Administrator"
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<string>("RolesName")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("RolesName", "UserId")
                        .HasName("pk_user_roles");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_roles_user_id");

                    b.ToTable("user_roles", "users");
                });

            modelBuilder.Entity("eMeetup.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "users");
                });

            modelBuilder.Entity("eMeetup.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "users");
                });

            modelBuilder.Entity("eMeetup.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "users");
                });

            modelBuilder.Entity("eMeetup.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "users");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("slug");

                    b.Property<Guid?>("TagGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_group_id");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("usage_count");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_tags_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_slug");

                    b.HasIndex("TagGroupId")
                        .HasDatabaseName("ix_tags_tag_group_id");

                    b.HasIndex("UsageCount")
                        .HasDatabaseName("ix_tags_usage_count");

                    b.ToTable("tags", "users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-aaaaaaaaaaaa"),
                            Description = "Jogging and running activities",
                            IsActive = true,
                            Name = "Running",
                            Slug = "running",
                            TagGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-bbbbbbbbbbbb"),
                            Description = "Pool swimming and training",
                            IsActive = true,
                            Name = "Swimming",
                            Slug = "swimming",
                            TagGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-cccccccccccc"),
                            Description = "Road and city bike rides",
                            IsActive = true,
                            Name = "Cycling",
                            Slug = "cycling",
                            TagGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-dddddddddddd"),
                            Description = "Fitness and strength training",
                            IsActive = true,
                            Name = "Gym Workout",
                            Slug = "gym-workout",
                            TagGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-eeeeeeeeeeee"),
                            Description = "Yoga and stretching sessions",
                            IsActive = true,
                            Name = "Yoga",
                            Slug = "yoga",
                            TagGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-aaaaaaaaaaaa"),
                            Description = "Downhill skiing on slopes",
                            IsActive = true,
                            Name = "Alpine Skiing",
                            Slug = "alpine-skiing",
                            TagGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-bbbbbbbbbbbb"),
                            Description = "Nordic skiing on trails",
                            IsActive = true,
                            Name = "Cross-Country Skiing",
                            Slug = "cross-country-skiing",
                            TagGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-cccccccccccc"),
                            Description = "Snowboarding on slopes and parks",
                            IsActive = true,
                            Name = "Snowboarding",
                            Slug = "snowboarding",
                            TagGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-dddddddddddd"),
                            Description = "Skating on ice rinks",
                            IsActive = true,
                            Name = "Ice Skating",
                            Slug = "ice-skating",
                            TagGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-eeeeeeeeeeee"),
                            Description = "Snow sliding with tubes",
                            IsActive = true,
                            Name = "Snow Tubing",
                            Slug = "snow-tubing",
                            TagGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-ffffffffffff"),
                            Description = "Hiking with snowshoes",
                            IsActive = true,
                            Name = "Winter Hiking",
                            Slug = "winter-hiking",
                            TagGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-aaaaaaaaaaaa"),
                            Description = "Day hiking on trails",
                            IsActive = true,
                            Name = "Hike",
                            Slug = "hike",
                            TagGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-bbbbbbbbbbbb"),
                            Description = "Multi-day cycling adventures",
                            IsActive = true,
                            Name = "Bike Touring",
                            Slug = "bike-touring",
                            TagGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-cccccccccccc"),
                            Description = "Outdoor meals in nature",
                            IsActive = true,
                            Name = "Picnic",
                            Slug = "picnic",
                            TagGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-dddddddddddd"),
                            Description = "Overnight stays in nature",
                            IsActive = true,
                            Name = "Camping",
                            Slug = "camping",
                            TagGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-eeeeeeeeeeee"),
                            Description = "Running on nature trails",
                            IsActive = true,
                            Name = "Trail Running",
                            Slug = "trail-running",
                            TagGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-aaaaaaaaaaaa"),
                            Description = "Lightweight portable rafting",
                            IsActive = true,
                            Name = "Packrafting",
                            Slug = "packrafting",
                            TagGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-bbbbbbbbbbbb"),
                            Description = "Stand-Up Paddleboarding",
                            IsActive = true,
                            Name = "SUP",
                            Slug = "sup",
                            TagGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-cccccccccccc"),
                            Description = "Kayaking on rivers and lakes",
                            IsActive = true,
                            Name = "Kayaking",
                            Slug = "kayaking",
                            TagGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-dddddddddddd"),
                            Description = "Canoe trips on calm waters",
                            IsActive = true,
                            Name = "Canoeing",
                            Slug = "canoeing",
                            TagGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-eeeeeeeeeeee"),
                            Description = "White water rafting",
                            IsActive = true,
                            Name = "Rafting",
                            Slug = "rafting",
                            TagGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-ffffffffffff"),
                            Description = "Swimming in lakes and seas",
                            IsActive = true,
                            Name = "Open Water Swimming",
                            Slug = "open-water-swimming",
                            TagGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-aaaaaaaaaaaa"),
                            Description = "Live music and concerts festivals",
                            IsActive = true,
                            Name = "Music Festival",
                            Slug = "music-festival",
                            TagGroupId = new Guid("55555555-5555-5555-5555-555555555555"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-bbbbbbbbbbbb"),
                            Description = "Culinary and gastronomy events",
                            IsActive = true,
                            Name = "Food Festival",
                            Slug = "food-festival",
                            TagGroupId = new Guid("55555555-5555-5555-5555-555555555555"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-cccccccccccc"),
                            Description = "Traditional and cultural celebrations",
                            IsActive = true,
                            Name = "Cultural Festival",
                            Slug = "cultural-festival",
                            TagGroupId = new Guid("55555555-5555-5555-5555-555555555555"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-dddddddddddd"),
                            Description = "Local city festivals and fairs",
                            IsActive = true,
                            Name = "City Celebration",
                            Slug = "city-celebration",
                            TagGroupId = new Guid("55555555-5555-5555-5555-555555555555"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-eeeeeeeeeeee"),
                            Description = "Craft beer and brewery events",
                            IsActive = true,
                            Name = "Beer Festival",
                            Slug = "beer-festival",
                            TagGroupId = new Guid("55555555-5555-5555-5555-555555555555"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-aaaaaaaaaaaa"),
                            Description = "Sightseeing in cities",
                            IsActive = true,
                            Name = "City Trip",
                            Slug = "city-trip",
                            TagGroupId = new Guid("66666666-6666-6666-6666-666666666666"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-bbbbbbbbbbbb"),
                            Description = "Gastronomy and local food tours",
                            IsActive = true,
                            Name = "Food Tourism",
                            Slug = "food-tourism",
                            TagGroupId = new Guid("66666666-6666-6666-6666-666666666666"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-cccccccccccc"),
                            Description = "Traveling by car",
                            IsActive = true,
                            Name = "Road Trip",
                            Slug = "road-trip",
                            TagGroupId = new Guid("66666666-6666-6666-6666-666666666666"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-dddddddddddd"),
                            Description = "Museums and architecture tours",
                            IsActive = true,
                            Name = "Cultural Tour",
                            Slug = "cultural-tour",
                            TagGroupId = new Guid("66666666-6666-6666-6666-666666666666"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-eeeeeeeeeeee"),
                            Description = "Short trips out of town",
                            IsActive = true,
                            Name = "Weekend Getaway",
                            Slug = "weekend-getaway",
                            TagGroupId = new Guid("66666666-6666-6666-6666-666666666666"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-aaaaaaaaaaaa"),
                            Description = "Movies and film screenings",
                            IsActive = true,
                            Name = "Cinema",
                            Slug = "cinema",
                            TagGroupId = new Guid("77777777-7777-7777-7777-777777777777"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-bbbbbbbbbbbb"),
                            Description = "Plays and theatrical performances",
                            IsActive = true,
                            Name = "Theater",
                            Slug = "theater",
                            TagGroupId = new Guid("77777777-7777-7777-7777-777777777777"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-cccccccccccc"),
                            Description = "Live music performances",
                            IsActive = true,
                            Name = "Concert",
                            Slug = "concert",
                            TagGroupId = new Guid("77777777-7777-7777-7777-777777777777"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-dddddddddddd"),
                            Description = "Rock and metal gigs",
                            IsActive = true,
                            Name = "Rock Show",
                            Slug = "rock-show",
                            TagGroupId = new Guid("77777777-7777-7777-7777-777777777777"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-eeeeeeeeeeee"),
                            Description = "Gallery and art shows",
                            IsActive = true,
                            Name = "Art Exhibition",
                            Slug = "art-exhibition",
                            TagGroupId = new Guid("77777777-7777-7777-7777-777777777777"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-ffffffffffff"),
                            Description = "Stand-up comedy performances",
                            IsActive = true,
                            Name = "Comedy Show",
                            Slug = "comedy-show",
                            TagGroupId = new Guid("77777777-7777-7777-7777-777777777777"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-aaaaaaaaaaaa"),
                            Description = "Bar and pub meetups",
                            IsActive = true,
                            Name = "Pub",
                            Slug = "pub",
                            TagGroupId = new Guid("88888888-8888-8888-8888-888888888888"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-bbbbbbbbbbbb"),
                            Description = "Outdoor cafes and terraces",
                            IsActive = true,
                            Name = "Patio",
                            Slug = "patio",
                            TagGroupId = new Guid("88888888-8888-8888-8888-888888888888"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-cccccccccccc"),
                            Description = "Casual coffee meetings",
                            IsActive = true,
                            Name = "Coffee Date",
                            Slug = "coffee-date",
                            TagGroupId = new Guid("88888888-8888-8888-8888-888888888888"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-dddddddddddd"),
                            Description = "Board game nights",
                            IsActive = true,
                            Name = "Board Games",
                            Slug = "board-games",
                            TagGroupId = new Guid("88888888-8888-8888-8888-888888888888"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-eeeeeeeeeeee"),
                            Description = "Relaxed park gatherings",
                            IsActive = true,
                            Name = "Picnic in Park",
                            Slug = "picnic-in-park",
                            TagGroupId = new Guid("88888888-8888-8888-8888-888888888888"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-aaaaaaaaaaaa"),
                            Description = "Swim, bike, run races",
                            IsActive = true,
                            Name = "Triathlon",
                            Slug = "triathlon",
                            TagGroupId = new Guid("99999999-9999-9999-9999-999999999999"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-bbbbbbbbbbbb"),
                            Description = "Running marathons in other cities",
                            IsActive = true,
                            Name = "Marathon",
                            Slug = "marathon",
                            TagGroupId = new Guid("99999999-9999-9999-9999-999999999999"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-cccccccccccc"),
                            Description = "Tough mudder and obstacle courses",
                            IsActive = true,
                            Name = "Obstacle Race",
                            Slug = "obstacle-race",
                            TagGroupId = new Guid("99999999-9999-9999-9999-999999999999"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-dddddddddddd"),
                            Description = "Competitive bike racing",
                            IsActive = true,
                            Name = "Cycling Race",
                            Slug = "cycling-race",
                            TagGroupId = new Guid("99999999-9999-9999-9999-999999999999"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-eeeeeeeeeeee"),
                            Description = "Open water or pool races",
                            IsActive = true,
                            Name = "Swimming Competition",
                            Slug = "swimming-competition",
                            TagGroupId = new Guid("99999999-9999-9999-9999-999999999999"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-ffffffffffff"),
                            Description = "Off-road running competitions",
                            IsActive = true,
                            Name = "Trail Running Race",
                            Slug = "trail-running-race",
                            TagGroupId = new Guid("99999999-9999-9999-9999-999999999999"),
                            UsageCount = 0
                        });
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Tags.TagGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tag_groups");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_tag_groups_display_order");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_tag_groups_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tag_groups_name");

                    b.ToTable("tag_groups", "users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Running, swimming, cycling and other sports activities",
                            DisplayOrder = 1,
                            Icon = "🏃",
                            IsActive = true,
                            Name = "Active Lifestyle"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Skiing, snowboarding, ice skating and snow tubing",
                            DisplayOrder = 2,
                            Icon = "❄️",
                            IsActive = true,
                            Name = "Winter Activities"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Hiking, biking tours and picnics in nature",
                            DisplayOrder = 3,
                            Icon = "⛰️",
                            IsActive = true,
                            Name = "Adventure & Outdoors"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Packrafting, SUP, kayaking and other water hikes",
                            DisplayOrder = 4,
                            Icon = "🚣",
                            IsActive = true,
                            Name = "Water Adventures"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Music, food and cultural festivals celebrations",
                            DisplayOrder = 5,
                            Icon = "🎪",
                            IsActive = true,
                            Name = "Festivals & Events"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "City trips, sightseeing, food tours and road trips",
                            DisplayOrder = 6,
                            Icon = "✈️",
                            IsActive = true,
                            Name = "Travel & Exploration"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Description = "Cinema, theater, concerts and rock shows",
                            DisplayOrder = 7,
                            Icon = "🎭",
                            IsActive = true,
                            Name = "Culture & Entertainment"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Description = "Pub meetups, terrace cafes and relaxing time",
                            DisplayOrder = 8,
                            Icon = "😎",
                            IsActive = true,
                            Name = "Chill & Hangout"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Description = "Marathons, triathlons, competitions and races in other cities",
                            DisplayOrder = 9,
                            Icon = "🏆",
                            IsActive = true,
                            Name = "Sports Events"
                        });
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.UserInterests.UserInterest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_interests");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_user_interests_created_at");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CreatedAt"), "brin");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_user_interests_tag_id");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TagId"), "hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_interests_user_id");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("UserId"), "hash");

                    b.HasIndex("UserId", "TagId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_interests_user_tag_unique");

                    b.ToTable("user_interests", "users", t =>
                        {
                            t.HasComment("Junction table for user interests and tags");
                        });
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.HasKey("Code")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", "users");

                    b.HasData(
                        new
                        {
                            Code = "users:read"
                        },
                        new
                        {
                            Code = "users:update"
                        },
                        new
                        {
                            Code = "tags:read"
                        },
                        new
                        {
                            Code = "event-statistics:read"
                        });
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Name")
                        .HasName("pk_roles");

                    b.ToTable("roles", "users");

                    b.HasData(
                        new
                        {
                            Name = "Member"
                        },
                        new
                        {
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("email");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_id");

                    b.Property<DateTime?>("LastActive")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture_url");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IdentityId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_identity_id");

                    b.ToTable("users", "users");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.UserPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_photos");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_photos_user_id");

                    b.HasIndex("UserId", "DisplayOrder")
                        .HasDatabaseName("ix_user_photos_user_id_display_order");

                    b.HasIndex("UserId", "IsPrimary")
                        .HasDatabaseName("ix_user_photos_user_id_is_primary")
                        .HasFilter("is_primary = true");

                    b.ToTable("user_photos", "users");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("eMeetup.Modules.Users.Domain.Users.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_code");

                    b.HasOne("eMeetup.Modules.Users.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_name");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("eMeetup.Modules.Users.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_roles_name");

                    b.HasOne("eMeetup.Modules.Users.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Tags.Tag", b =>
                {
                    b.HasOne("eMeetup.Modules.Users.Domain.Tags.TagGroup", "TagGroup")
                        .WithMany("Tags")
                        .HasForeignKey("TagGroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tags_tag_group_tag_group_id");

                    b.Navigation("TagGroup");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.UserInterests.UserInterest", b =>
                {
                    b.HasOne("eMeetup.Modules.Users.Domain.Tags.Tag", "Tag")
                        .WithMany("UserInterests")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_interests_tags_tag_id");

                    b.HasOne("eMeetup.Modules.Users.Domain.Users.User", "User")
                        .WithMany("Interests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_interests_users_user_id");

                    b.Navigation("Tag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.User", b =>
                {
                    b.OwnsOne("eMeetup.Modules.Users.Domain.Users.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("location_city");

                            b1.Property<double>("Latitude")
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("location_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("location_longitude");

                            b1.Property<string>("Street")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("location_street");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.UserPhoto", b =>
                {
                    b.HasOne("eMeetup.Modules.Users.Domain.Users.User", "User")
                        .WithMany("Photos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_photos_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Tags.Tag", b =>
                {
                    b.Navigation("UserInterests");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Tags.TagGroup", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.User", b =>
                {
                    b.Navigation("Interests");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
