// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eMeetup.Modules.Users.Infrastructure.Database;

#nullable disable

namespace eMeetup.Modules.Users.Infrastructure.Database.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20260218155539_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("users")
                .HasAnnotation("ProductVersion", "10.0.0-rc.1.25451.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<string>("PermissionCode")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission_code");

                    b.Property<string>("RoleName")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("PermissionCode", "RoleName")
                        .HasName("pk_role_permissions");

                    b.HasIndex("RoleName")
                        .HasDatabaseName("ix_role_permissions_role_name");

                    b.ToTable("role_permissions", "users");

                    b.HasData(
                        new
                        {
                            PermissionCode = "users:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "users:update",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "tags:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "users:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "users:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "tags:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "event-statistics:read",
                            RoleName = "Administrator"
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<string>("RolesName")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("RolesName", "UserId")
                        .HasName("pk_user_roles");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_roles_user_id");

                    b.ToTable("user_roles", "users");
                });

            modelBuilder.Entity("eMeetup.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "users");
                });

            modelBuilder.Entity("eMeetup.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "users");
                });

            modelBuilder.Entity("eMeetup.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "users");
                });

            modelBuilder.Entity("eMeetup.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "users");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("slug");

                    b.Property<Guid?>("TagGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_group_id");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("usage_count");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_tags_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_slug");

                    b.HasIndex("TagGroupId")
                        .HasDatabaseName("ix_tags_tag_group_id");

                    b.HasIndex("UsageCount")
                        .HasDatabaseName("ix_tags_usage_count");

                    b.ToTable("tags", "users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-aaaaaaaaaaaa"),
                            Description = "Paddle through waters in a kayak",
                            IsActive = true,
                            Name = "Kayaking",
                            Slug = "kayaking",
                            TagGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-bbbbbbbbbbbb"),
                            Description = "White water rafting adventures",
                            IsActive = true,
                            Name = "Rafting",
                            Slug = "rafting",
                            TagGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-cccccccccccc"),
                            Description = "Ride the waves",
                            IsActive = true,
                            Name = "Surfing",
                            Slug = "surfing",
                            TagGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-dddddddddddd"),
                            Description = "Explore underwater worlds",
                            IsActive = true,
                            Name = "Scuba Diving",
                            Slug = "scuba-diving",
                            TagGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-eeeeeeeeeeee"),
                            Description = "Surface underwater exploration",
                            IsActive = true,
                            Name = "Snorkeling",
                            Slug = "snorkeling",
                            TagGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-ffffffffffff"),
                            Description = "Paddleboarding on calm waters",
                            IsActive = true,
                            Name = "Stand Up Paddleboarding",
                            Slug = "stand-up-paddleboarding",
                            TagGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            Description = "Skiing on water surface",
                            IsActive = true,
                            Name = "Waterskiing",
                            Slug = "waterskiing",
                            TagGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-222222222222"),
                            Description = "Board riding on wake",
                            IsActive = true,
                            Name = "Wakeboarding",
                            Slug = "wakeboarding",
                            TagGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-333333333333"),
                            Description = "Wind-powered boating",
                            IsActive = true,
                            Name = "Sailing",
                            Slug = "sailing",
                            TagGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-444444444444"),
                            Description = "Paddle in open canoes",
                            IsActive = true,
                            Name = "Canoeing",
                            Slug = "canoeing",
                            TagGroupId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-aaaaaaaaaaaa"),
                            Description = "Single day trail walks",
                            IsActive = true,
                            Name = "Day Hiking",
                            Slug = "day-hiking",
                            TagGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-bbbbbbbbbbbb"),
                            Description = "Multi-day hiking with gear",
                            IsActive = true,
                            Name = "Backpacking",
                            Slug = "backpacking",
                            TagGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-cccccccccccc"),
                            Description = "Running on nature trails",
                            IsActive = true,
                            Name = "Trail Running",
                            Slug = "trail-running",
                            TagGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-dddddddddddd"),
                            Description = "Summiting mountain peaks",
                            IsActive = true,
                            Name = "Peak Bagging",
                            Slug = "peak-bagging",
                            TagGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-eeeeeeeeeeee"),
                            Description = "Leisurely nature exploration",
                            IsActive = true,
                            Name = "Nature Walks",
                            Slug = "nature-walks",
                            TagGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-ffffffffffff"),
                            Description = "Walking with poles",
                            IsActive = true,
                            Name = "Nordic Walking",
                            Slug = "nordic-walking",
                            TagGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-111111111111"),
                            Description = "Technical hiking with hands-on climbing",
                            IsActive = true,
                            Name = "Scrambling",
                            Slug = "scrambling",
                            TagGroupId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("cccccccc-3333-3333-3333-aaaaaaaaaaaa"),
                            Description = "Traditional tent camping",
                            IsActive = true,
                            Name = "Tent Camping",
                            Slug = "tent-camping",
                            TagGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("cccccccc-3333-3333-3333-bbbbbbbbbbbb"),
                            Description = "Camping with recreational vehicles",
                            IsActive = true,
                            Name = "RV Camping",
                            Slug = "rv-camping",
                            TagGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("cccccccc-3333-3333-3333-cccccccccccc"),
                            Description = "Remote wilderness camping",
                            IsActive = true,
                            Name = "Backcountry Camping",
                            Slug = "backcountry-camping",
                            TagGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("cccccccc-3333-3333-3333-dddddddddddd"),
                            Description = "Luxury camping experience",
                            IsActive = true,
                            Name = "Glamping",
                            Slug = "glamping",
                            TagGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("cccccccc-3333-3333-3333-eeeeeeeeeeee"),
                            Description = "Sleeping in hammocks",
                            IsActive = true,
                            Name = "Hammock Camping",
                            Slug = "hammock-camping",
                            TagGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("cccccccc-3333-3333-3333-ffffffffffff"),
                            Description = "Cold weather camping",
                            IsActive = true,
                            Name = "Winter Camping",
                            Slug = "winter-camping",
                            TagGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("cccccccc-3333-3333-3333-111111111111"),
                            Description = "Camping on or near beaches",
                            IsActive = true,
                            Name = "Beach Camping",
                            Slug = "beach-camping",
                            TagGroupId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("dddddddd-4444-4444-4444-aaaaaaaaaaaa"),
                            Description = "Climbing natural rock formations",
                            IsActive = true,
                            Name = "Rock Climbing",
                            Slug = "rock-climbing",
                            TagGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("dddddddd-4444-4444-4444-bbbbbbbbbbbb"),
                            Description = "Low-level climbing without ropes",
                            IsActive = true,
                            Name = "Bouldering",
                            Slug = "bouldering",
                            TagGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("dddddddd-4444-4444-4444-cccccccccccc"),
                            Description = "Climbing with fixed anchors",
                            IsActive = true,
                            Name = "Sport Climbing",
                            Slug = "sport-climbing",
                            TagGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("dddddddd-4444-4444-4444-dddddddddddd"),
                            Description = "Placing own protection while climbing",
                            IsActive = true,
                            Name = "Traditional Climbing",
                            Slug = "traditional-climbing",
                            TagGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("dddddddd-4444-4444-4444-eeeeeeeeeeee"),
                            Description = "Climbing frozen waterfalls and ice formations",
                            IsActive = true,
                            Name = "Ice Climbing",
                            Slug = "ice-climbing",
                            TagGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("dddddddd-4444-4444-4444-ffffffffffff"),
                            Description = "Mountain climbing expeditions",
                            IsActive = true,
                            Name = "Mountaineering",
                            Slug = "mountaineering",
                            TagGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("dddddddd-4444-4444-4444-111111111111"),
                            Description = "Protected climbing routes with cables",
                            IsActive = true,
                            Name = "Via Ferrata",
                            Slug = "via-ferrata",
                            TagGroupId = new Guid("44444444-4444-4444-4444-444444444444"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-5555-5555-5555-aaaaaaaaaaaa"),
                            Description = "Alpine skiing on slopes",
                            IsActive = true,
                            Name = "Downhill Skiing",
                            Slug = "downhill-skiing",
                            TagGroupId = new Guid("55555555-5555-5555-5555-555555555555"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-5555-5555-5555-bbbbbbbbbbbb"),
                            Description = "Nordic skiing on trails",
                            IsActive = true,
                            Name = "Cross-Country Skiing",
                            Slug = "cross-country-skiing",
                            TagGroupId = new Guid("55555555-5555-5555-5555-555555555555"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-5555-5555-5555-cccccccccccc"),
                            Description = "Riding snow on a board",
                            IsActive = true,
                            Name = "Snowboarding",
                            Slug = "snowboarding",
                            TagGroupId = new Guid("55555555-5555-5555-5555-555555555555"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-5555-5555-5555-dddddddddddd"),
                            Description = "Walking on snow with specialized footwear",
                            IsActive = true,
                            Name = "Snowshoeing",
                            Slug = "snowshoeing",
                            TagGroupId = new Guid("55555555-5555-5555-5555-555555555555"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-5555-5555-5555-eeeeeeeeeeee"),
                            Description = "Skating on frozen surfaces",
                            IsActive = true,
                            Name = "Ice Skating",
                            Slug = "ice-skating",
                            TagGroupId = new Guid("55555555-5555-5555-5555-555555555555"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-5555-5555-5555-ffffffffffff"),
                            Description = "Riding motorized snow vehicles",
                            IsActive = true,
                            Name = "Snowmobiling",
                            Slug = "snowmobiling",
                            TagGroupId = new Guid("55555555-5555-5555-5555-555555555555"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-5555-5555-5555-111111111111"),
                            Description = "Skiing in unpatrolled areas",
                            IsActive = true,
                            Name = "Backcountry Skiing",
                            Slug = "backcountry-skiing",
                            TagGroupId = new Guid("55555555-5555-5555-5555-555555555555"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("ffffffff-6666-6666-6666-aaaaaaaaaaaa"),
                            Description = "Off-road cycling on trails",
                            IsActive = true,
                            Name = "Mountain Biking",
                            Slug = "mountain-biking",
                            TagGroupId = new Guid("66666666-6666-6666-6666-666666666666"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("ffffffff-6666-6666-6666-bbbbbbbbbbbb"),
                            Description = "Cycling on paved roads",
                            IsActive = true,
                            Name = "Road Cycling",
                            Slug = "road-cycling",
                            TagGroupId = new Guid("66666666-6666-6666-6666-666666666666"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("ffffffff-6666-6666-6666-cccccccccccc"),
                            Description = "Cycling on gravel roads",
                            IsActive = true,
                            Name = "Gravel Cycling",
                            Slug = "gravel-cycling",
                            TagGroupId = new Guid("66666666-6666-6666-6666-666666666666"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("ffffffff-6666-6666-6666-dddddddddddd"),
                            Description = "Bicycle motocross",
                            IsActive = true,
                            Name = "BMX",
                            Slug = "bmx",
                            TagGroupId = new Guid("66666666-6666-6666-6666-666666666666"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("ffffffff-6666-6666-6666-eeeeeeeeeeee"),
                            Description = "Mixed terrain cycling with obstacles",
                            IsActive = true,
                            Name = "Cyclocross",
                            Slug = "cyclocross",
                            TagGroupId = new Guid("66666666-6666-6666-6666-666666666666"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("ffffffff-6666-6666-6666-ffffffffffff"),
                            Description = "Cycling with oversized tires on soft surfaces",
                            IsActive = true,
                            Name = "Fat Biking",
                            Slug = "fat-biking",
                            TagGroupId = new Guid("66666666-6666-6666-6666-666666666666"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("ffffffff-6666-6666-6666-111111111111"),
                            Description = "Multi-day cycling trips with luggage",
                            IsActive = true,
                            Name = "Bike Touring",
                            Slug = "bike-touring",
                            TagGroupId = new Guid("66666666-6666-6666-6666-666666666666"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-7777-7777-7777-aaaaaaaaaaaa"),
                            Description = "Observing birds in their habitat",
                            IsActive = true,
                            Name = "Bird Watching",
                            Slug = "bird-watching",
                            TagGroupId = new Guid("77777777-7777-7777-7777-777777777777"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-7777-7777-7777-bbbbbbbbbbbb"),
                            Description = "Photographing animals in nature",
                            IsActive = true,
                            Name = "Wildlife Photography",
                            Slug = "wildlife-photography",
                            TagGroupId = new Guid("77777777-7777-7777-7777-777777777777"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-7777-7777-7777-cccccccccccc"),
                            Description = "Capturing landscapes and natural scenes",
                            IsActive = true,
                            Name = "Nature Photography",
                            Slug = "nature-photography",
                            TagGroupId = new Guid("77777777-7777-7777-7777-777777777777"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-7777-7777-7777-dddddddddddd"),
                            Description = "Observing celestial objects",
                            IsActive = true,
                            Name = "Stargazing",
                            Slug = "stargazing",
                            TagGroupId = new Guid("77777777-7777-7777-7777-777777777777"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-7777-7777-7777-eeeeeeeeeeee"),
                            Description = "Studying plants and wildflowers",
                            IsActive = true,
                            Name = "Botany",
                            Slug = "botany",
                            TagGroupId = new Guid("77777777-7777-7777-7777-777777777777"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-7777-7777-7777-ffffffffffff"),
                            Description = "Outdoor treasure hunting with GPS",
                            IsActive = true,
                            Name = "Geocaching",
                            Slug = "geocaching",
                            TagGroupId = new Guid("77777777-7777-7777-7777-777777777777"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-7777-7777-7777-111111111111"),
                            Description = "Searching for wild food",
                            IsActive = true,
                            Name = "Foraging",
                            Slug = "foraging",
                            TagGroupId = new Guid("77777777-7777-7777-7777-777777777777"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-8888-8888-8888-aaaaaaaaaaaa"),
                            Description = "Fishing with artificial flies",
                            IsActive = true,
                            Name = "Fly Fishing",
                            Slug = "fly-fishing",
                            TagGroupId = new Guid("88888888-8888-8888-8888-888888888888"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-8888-8888-8888-bbbbbbbbbbbb"),
                            Description = "Fishing in ocean waters",
                            IsActive = true,
                            Name = "Deep Sea Fishing",
                            Slug = "deep-sea-fishing",
                            TagGroupId = new Guid("88888888-8888-8888-8888-888888888888"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-8888-8888-8888-cccccccccccc"),
                            Description = "Fishing through holes in ice",
                            IsActive = true,
                            Name = "Ice Fishing",
                            Slug = "ice-fishing",
                            TagGroupId = new Guid("88888888-8888-8888-8888-888888888888"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-8888-8888-8888-dddddddddddd"),
                            Description = "Fishing in lakes and rivers",
                            IsActive = true,
                            Name = "Freshwater Fishing",
                            Slug = "freshwater-fishing",
                            TagGroupId = new Guid("88888888-8888-8888-8888-888888888888"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-8888-8888-8888-eeeeeeeeeeee"),
                            Description = "Fishing from a kayak",
                            IsActive = true,
                            Name = "Kayak Fishing",
                            Slug = "kayak-fishing",
                            TagGroupId = new Guid("88888888-8888-8888-8888-888888888888"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-8888-8888-8888-ffffffffffff"),
                            Description = "Fishing with a spear",
                            IsActive = true,
                            Name = "Spearfishing",
                            Slug = "spearfishing",
                            TagGroupId = new Guid("88888888-8888-8888-8888-888888888888"),
                            UsageCount = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-8888-8888-8888-111111111111"),
                            Description = "Fishing from shoreline",
                            IsActive = true,
                            Name = "Surf Fishing",
                            Slug = "surf-fishing",
                            TagGroupId = new Guid("88888888-8888-8888-8888-888888888888"),
                            UsageCount = 0
                        });
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Tags.TagGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tag_groups");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_tag_groups_display_order");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_tag_groups_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tag_groups_name");

                    b.ToTable("tag_groups", "users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Activities related to water-based recreation",
                            DisplayOrder = 1,
                            Icon = "🌊",
                            IsActive = true,
                            Name = "Water Sports"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Trail walking, backpacking, and mountain hiking",
                            DisplayOrder = 2,
                            Icon = "🥾",
                            IsActive = true,
                            Name = "Hiking & Trekking"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Overnight outdoor stays and wilderness camping",
                            DisplayOrder = 3,
                            Icon = "⛺",
                            IsActive = true,
                            Name = "Camping"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "Rock climbing, bouldering, and mountaineering",
                            DisplayOrder = 4,
                            Icon = "🧗",
                            IsActive = true,
                            Name = "Climbing"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "Snow and ice activities",
                            DisplayOrder = 5,
                            Icon = "⛷️",
                            IsActive = true,
                            Name = "Winter Sports"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "Biking, mountain biking, and cycling tours",
                            DisplayOrder = 6,
                            Icon = "🚴",
                            IsActive = true,
                            Name = "Cycling"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Description = "Bird watching, nature photography, and wildlife observation",
                            DisplayOrder = 7,
                            Icon = "🦌",
                            IsActive = true,
                            Name = "Wildlife & Nature"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Description = "Angling, fly fishing, and ice fishing",
                            DisplayOrder = 8,
                            Icon = "🎣",
                            IsActive = true,
                            Name = "Fishing"
                        });
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.UserInterests.UserInterest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_interests");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_user_interests_created_at");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CreatedAt"), "brin");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_user_interests_tag_id");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TagId"), "hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_interests_user_id");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("UserId"), "hash");

                    b.HasIndex("UserId", "TagId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_interests_user_tag_unique");

                    b.ToTable("user_interests", "users", t =>
                        {
                            t.HasComment("Junction table for user interests and tags");
                        });
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.HasKey("Code")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", "users");

                    b.HasData(
                        new
                        {
                            Code = "users:read"
                        },
                        new
                        {
                            Code = "users:update"
                        },
                        new
                        {
                            Code = "tags:read"
                        },
                        new
                        {
                            Code = "event-statistics:read"
                        });
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Name")
                        .HasName("pk_roles");

                    b.ToTable("roles", "users");

                    b.HasData(
                        new
                        {
                            Name = "Member"
                        },
                        new
                        {
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("email");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_id");

                    b.Property<DateTime?>("LastActive")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_picture_url");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IdentityId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_identity_id");

                    b.ToTable("users", "users");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.UserPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_photos");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_photos_user_id");

                    b.HasIndex("UserId", "DisplayOrder")
                        .HasDatabaseName("ix_user_photos_user_id_display_order");

                    b.HasIndex("UserId", "IsPrimary")
                        .HasDatabaseName("ix_user_photos_user_id_is_primary")
                        .HasFilter("is_primary = true");

                    b.ToTable("user_photos", "users");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("eMeetup.Modules.Users.Domain.Users.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_code");

                    b.HasOne("eMeetup.Modules.Users.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_name");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("eMeetup.Modules.Users.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_roles_name");

                    b.HasOne("eMeetup.Modules.Users.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Tags.Tag", b =>
                {
                    b.HasOne("eMeetup.Modules.Users.Domain.Tags.TagGroup", "TagGroup")
                        .WithMany("Tags")
                        .HasForeignKey("TagGroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_tags_tag_group_tag_group_id");

                    b.Navigation("TagGroup");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.UserInterests.UserInterest", b =>
                {
                    b.HasOne("eMeetup.Modules.Users.Domain.Tags.Tag", "Tag")
                        .WithMany("UserInterests")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_interests_tags_tag_id");

                    b.HasOne("eMeetup.Modules.Users.Domain.Users.User", "User")
                        .WithMany("Interests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_interests_users_user_id");

                    b.Navigation("Tag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.User", b =>
                {
                    b.OwnsOne("eMeetup.Modules.Users.Domain.Users.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("location_city");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("location_country");

                            b1.Property<double>("Latitude")
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("location_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("location_longitude");

                            b1.HasKey("UserId");

                            b1.ToTable("users", "users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.UserPhoto", b =>
                {
                    b.HasOne("eMeetup.Modules.Users.Domain.Users.User", "User")
                        .WithMany("Photos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_photos_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Tags.Tag", b =>
                {
                    b.Navigation("UserInterests");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Tags.TagGroup", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.User", b =>
                {
                    b.Navigation("Interests");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
