// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eMeetup.Modules.Users.Infrastructure.Database;

#nullable disable

namespace eMeetup.Modules.Users.Infrastructure.Database.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    partial class UsersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("users")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<string>("PermissionCode")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission_code");

                    b.Property<string>("RoleName")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("PermissionCode", "RoleName")
                        .HasName("pk_role_permissions");

                    b.HasIndex("RoleName")
                        .HasDatabaseName("ix_role_permissions_role_name");

                    b.ToTable("role_permissions", "users");

                    b.HasData(
                        new
                        {
                            PermissionCode = "users:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "users:update",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "tags:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "events:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "events:search",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "events:update",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "users:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "users:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "tags:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "events:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "events:search",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "events:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "event-statistics:read",
                            RoleName = "Administrator"
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<string>("RolesName")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("RolesName", "UserId")
                        .HasName("pk_user_roles");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_roles_user_id");

                    b.ToTable("user_roles", "users");
                });

            modelBuilder.Entity("eMeetup.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "users");
                });

            modelBuilder.Entity("eMeetup.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "users");
                });

            modelBuilder.Entity("eMeetup.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "users");
                });

            modelBuilder.Entity("eMeetup.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "users");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Tags.TagGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tag_group");

                    b.ToTable("tag_group", "users");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Tags.UserTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<Guid?>("TagGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_group_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer")
                        .HasColumnName("usage_count");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_tag");

                    b.HasIndex("TagGroupId")
                        .HasDatabaseName("ix_user_tag_tag_group_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_tag_user_id");

                    b.ToTable("user_tag", "users");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.HasKey("Code")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", "users");

                    b.HasData(
                        new
                        {
                            Code = "users:read"
                        },
                        new
                        {
                            Code = "users:update"
                        },
                        new
                        {
                            Code = "tags:read"
                        },
                        new
                        {
                            Code = "events:read"
                        },
                        new
                        {
                            Code = "events:search"
                        },
                        new
                        {
                            Code = "events:update"
                        },
                        new
                        {
                            Code = "event-statistics:read"
                        });
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Name")
                        .HasName("pk_roles");

                    b.ToTable("roles", "users");

                    b.HasData(
                        new
                        {
                            Name = "Member"
                        },
                        new
                        {
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<Guid>("IdentityId")
                        .HasMaxLength(255)
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at");

                    b.Property<DateTime?>("LastStatusChangeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_status_change_at");

                    b.Property<bool>("ProfileCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("profile_completed");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2)
                        .HasColumnName("status");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("status_reason");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_users_created_at");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IdentityId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_identity_id");

                    b.HasIndex("LastActiveAt")
                        .HasDatabaseName("ix_users_last_active_at");

                    b.HasIndex("ProfileCompleted")
                        .HasDatabaseName("ix_users_profile_completed");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_users_status");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.HasIndex("Status", "ProfileCompleted")
                        .HasDatabaseName("ix_users_status_profile_completed");

                    b.ToTable("users", "users");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.UserFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_favorites");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_user_favorites_is_active");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("ix_user_favorites_target_user_id");

                    b.HasIndex("UserId", "TargetUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_favorites_user_target_active")
                        .HasFilter("\"is_active\" = true");

                    b.ToTable("user_favorites", "users");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastNotificationSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_notification_sent_at");

                    b.Property<DateTime>("SubscribedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscribed_at");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_user_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UnsubscribedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unsubscribed_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_subscriptions");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_user_subscriptions_is_active");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("ix_user_subscriptions_target_user_id");

                    b.HasIndex("UserId", "TargetUserId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_user_subscriptions_user_target_type_active")
                        .HasFilter("\"is_active\" = true");

                    b.ToTable("user_subscriptions", "users");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("eMeetup.Modules.Users.Domain.Users.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_code");

                    b.HasOne("eMeetup.Modules.Users.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_name");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("eMeetup.Modules.Users.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_roles_name");

                    b.HasOne("eMeetup.Modules.Users.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Tags.UserTag", b =>
                {
                    b.HasOne("eMeetup.Modules.Users.Domain.Tags.TagGroup", "TagGroup")
                        .WithMany("Tags")
                        .HasForeignKey("TagGroupId")
                        .HasConstraintName("fk_user_tag_tag_group_tag_group_id");

                    b.HasOne("eMeetup.Modules.Users.Domain.Users.User", null)
                        .WithMany("UserTags")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_user_tag_users_user_id");

                    b.Navigation("TagGroup");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.User", b =>
                {
                    b.OwnsOne("eMeetup.Modules.Users.Domain.Users.UserProfile", "Profile", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("AvatarUrl")
                                .HasMaxLength(500);

                            b1.Property<string>("Bio")
                                .HasMaxLength(500);

                            b1.Property<string>("City")
                                .HasMaxLength(100);

                            b1.Property<string>("Country")
                                .HasMaxLength(100);

                            b1.Property<DateTime?>("DateOfBirth");

                            b1.Property<string>("Gender")
                                .HasMaxLength(20);

                            b1.Property<string>("Instagram")
                                .HasMaxLength(50);

                            b1.Property<string>("Interests")
                                .HasMaxLength(500);

                            b1.Property<bool>("IsEmailVerified");

                            b1.Property<bool>("IsPhoneVerified");

                            b1.Property<bool>("IsPublic");

                            b1.Property<string>("Languages")
                                .HasMaxLength(100);

                            b1.Property<DateTime?>("LastProfileUpdate");

                            b1.Property<double?>("Latitude")
                                .HasPrecision(10, 8);

                            b1.Property<double?>("Longitude")
                                .HasPrecision(11, 8);

                            b1.Property<string>("Phone")
                                .HasMaxLength(20);

                            b1.Property<string>("Telegram")
                                .HasMaxLength(50);

                            b1.Property<string>("TimeZone")
                                .HasMaxLength(50);

                            b1.HasKey("UserId");

                            b1.ToTable("users", "users");

                            b1
                                .ToJson("profile")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");

                            b1.OwnsOne("eMeetup.Modules.Users.Domain.Activities.ActivityPreferences", "ActivityPreferences", b2 =>
                                {
                                    b2.Property<Guid>("UserProfileUserId");

                                    b2.Property<string>("ActivityLevels")
                                        .IsRequired();

                                    b2.Property<int?>("MaxDistanceKm");

                                    b2.Property<int?>("MaxParticipants");

                                    b2.Property<int?>("MinParticipants");

                                    b2.Property<string>("PreferredActivities")
                                        .IsRequired();

                                    b2.Property<string>("PreferredDays")
                                        .IsRequired();

                                    b2.Property<int?>("PreferredTimeOfDay");

                                    b2.HasKey("UserProfileUserId")
                                        .HasName("pk_users");

                                    b2.ToTable("users", "users");

                                    b2.WithOwner()
                                        .HasForeignKey("UserProfileUserId")
                                        .HasConstraintName("fk_users_users_user_profile_user_id");
                                });

                            b1.OwnsOne("eMeetup.Modules.Users.Domain.Activities.AvailabilityStatus", "AvailabilityStatus", b2 =>
                                {
                                    b2.Property<Guid>("UserProfileUserId");

                                    b2.Property<DateTime?>("AvailableFrom");

                                    b2.Property<DateTime?>("AvailableUntil");

                                    b2.Property<string>("StatusMessage")
                                        .HasMaxLength(200);

                                    b2.Property<int>("Type");

                                    b2.HasKey("UserProfileUserId")
                                        .HasName("pk_users");

                                    b2.ToTable("users", "users");

                                    b2.WithOwner()
                                        .HasForeignKey("UserProfileUserId")
                                        .HasConstraintName("fk_users_users_user_profile_user_id");
                                });

                            b1.Navigation("ActivityPreferences")
                                .IsRequired();

                            b1.Navigation("AvailabilityStatus")
                                .IsRequired();
                        });

                    b.OwnsMany("eMeetup.Modules.Users.Domain.Photos.UserPhoto", "_photos", b1 =>
                        {
                            b1.Property<Guid>("user_id")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id")
                                .HasDefaultValueSql("gen_random_uuid()");

                            b1.Property<string>("ContentType")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("content_type");

                            b1.Property<int>("DisplayOrder")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("display_order");

                            b1.Property<string>("FileName")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("file_name");

                            b1.Property<long?>("FileSize")
                                .HasColumnType("bigint")
                                .HasColumnName("file_size");

                            b1.Property<bool>("IsPrimary")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("is_primary");

                            b1.Property<string>("ThumbnailUrl")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("thumbnail_url");

                            b1.Property<DateTime>("UploadedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("uploaded_at")
                                .HasDefaultValueSql("CURRENT_TIMESTAMP");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("url");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.HasKey("user_id", "Id")
                                .HasName("pk_user_photos");

                            b1.HasIndex("DisplayOrder")
                                .HasDatabaseName("ix_user_photos_display_order");

                            b1.HasIndex("user_id")
                                .HasDatabaseName("ix_user_photos_user_id");

                            b1.HasIndex("user_id", "IsPrimary")
                                .HasDatabaseName("ix_user_photos_user_id_is_primary")
                                .HasFilter("\"is_primary\" = true");

                            b1.ToTable("user_photos", "users", t =>
                                {
                                    t.Property("user_id")
                                        .HasColumnName("user_id1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("user_id")
                                .HasConstraintName("fk_user_photos_users_user_id");
                        });

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("_photos");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.UserFavorite", b =>
                {
                    b.HasOne("eMeetup.Modules.Users.Domain.Users.User", "TargetUser")
                        .WithMany("FavoritedBy")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_favorites_users_target_user_id");

                    b.HasOne("eMeetup.Modules.Users.Domain.Users.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_favorites_users_user_id");

                    b.Navigation("TargetUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.UserSubscription", b =>
                {
                    b.HasOne("eMeetup.Modules.Users.Domain.Users.User", "TargetUser")
                        .WithMany("Subscribers")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_subscriptions_users_target_user_id");

                    b.HasOne("eMeetup.Modules.Users.Domain.Users.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_subscriptions_users_user_id");

                    b.Navigation("TargetUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Tags.TagGroup", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("eMeetup.Modules.Users.Domain.Users.User", b =>
                {
                    b.Navigation("FavoritedBy");

                    b.Navigation("Favorites");

                    b.Navigation("Subscribers");

                    b.Navigation("Subscriptions");

                    b.Navigation("UserTags");
                });
#pragma warning restore 612, 618
        }
    }
}
